# Generated by Django 2.2.10 on 2020-09-07 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20200907_1410'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post1',
            new_name='post2',
        ),
    ]
