# Generated by Django 2.2.10 on 2020-09-07 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_postview'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category_index',
            field=models.ManyToManyField(to='blog.Category'),
        ),
    ]
