# Generated by Django 2.2.10 on 2020-09-18 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_blog_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='slug',
        ),
    ]
